// Generates the static pages that sit next to the hand-written index.html:
//   work/index.html, work/<slug>/index.html, 404.html and sitemap.xml.
// The header, contact block and footer are copied from index.html (between the
// <!-- shared:... --> markers), so edit them there and rerun:  node tools/build.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { projects, LAYERS } from './projects.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://notechdebt.dev';
const index = readFileSync(join(ROOT, 'index.html'), 'utf8');

function shared(name) {
  const m = index.match(new RegExp(`<!-- shared:${name}(?:\\s[^>]*)?-->\\n?([\\s\\S]*?)<!-- /shared:${name} -->`));
  if (!m) throw new Error(`index.html is missing the <!-- shared:${name} --> block`);
  return m[1].trimEnd();
}
const HEAD = shared('head'), HEADER = shared('header'), CONTACT = shared('contact'), FOOTER = shared('footer');

const esc = (t) => String(t).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const host = (u) => u.replace(/^https?:\/\//, '').replace(/\/$/, '');
const ld = (o) => `<script type="application/ld+json">\n${JSON.stringify(o, null, 2).replace(/</g, '\\u003c')}\n</script>`;

function img(slug, [w, h], alt, sizes, extra = '') {
  return `<img src="/img/${slug}-640.webp" srcset="/img/${slug}-640.webp 640w, /img/${slug}-960.webp 960w, /img/${slug}.webp 1280w" sizes="${sizes}" width="${w}" height="${h}" alt="${esc(alt)}"${extra}>`;
}

// The day a page first went into git, so its publish date stays put across rebuilds; today for a new page.
function published(rel) {
  try {
    const first = execFileSync('git', ['log', '--diff-filter=A', '--format=%cs', '--', rel], { cwd: ROOT, encoding: 'utf8' }).trim().split('\n').pop();
    if (first) return first;
  } catch {}
  return new Date().toLocaleDateString('en-CA');
}

function page({ title, description, path, ogImage, ogAlt, ogType = 'website', robots = 'index, follow, max-image-preview:large', date, jsonld, main }) {
  const url = SITE + path;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<meta name="robots" content="${robots}">
${robots.startsWith('noindex') ? '' : `<link rel="canonical" href="${url}">\n`}${HEAD}
<meta property="og:type" content="${ogType}">
<meta property="og:url" content="${url}">
<meta property="og:site_name" content="notechdebt">
<meta property="og:locale" content="en_US">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:image" content="${SITE}${ogImage}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${esc(ogAlt)}">
${date ? `<meta property="article:published_time" content="${date}">\n<meta name="publish_date" property="og:publish_date" content="${date}">\n` : ''}<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@notechdebt">
<meta name="twitter:creator" content="@notechdebt">
${jsonld ? ld(jsonld) + '\n' : ''}</head>
<body>

<!-- generated by tools/build.mjs from tools/projects.mjs; edit those, not this file -->
${HEADER}

<main id="top" class="pv">
${main}
${CONTACT}
</main>

${FOOTER}
</body>
</html>
`;
}

const WORK = { title: 'Case Studies: AI, SaaS, ERP and E-commerce Builds | notechdebt', path: '/work/' };

function breadcrumb(path, items) {
  return {
    '@type': 'BreadcrumbList', '@id': SITE + path + '#breadcrumb',
    itemListElement: items.map(([name, p], i) => ({ '@type': 'ListItem', position: i + 1, name, ...(p ? { item: SITE + p } : {}) }))
  };
}

function relatedCard(p, d) {
  return `<div class="cell" data-sr="up" data-d="${d}"><a class="card rel-card" href="/work/${p.slug}/"><span class="thumb">${img(p.slug, p.shot, p.alt, '(max-width: 760px) calc(100vw - 32px), 420px', ' loading="lazy" decoding="async"')}</span><span class="row"><span>${esc(p.tag)}</span><span>→</span></span><h3 class="name">${esc(p.name)}</h3><span class="desc">${esc(p.one)}</span></a></div>`;
}

function projectPage(p, i) {
  const path = `/work/${p.slug}/`;
  const layers = LAYERS.map(([k, label]) => `<em class="${p.on.includes(k) ? 'on' : ''}">${label}</em>`).join('');
  const rel = [1, 2, 3].map((k) => relatedCard(projects[(i + k) % projects.length], k - 1)).join('\n        ');
  const main = `  <div class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/work/">Case studies</a><span aria-hidden="true">/</span><span aria-current="page">${esc(p.name)}</span></nav>
    <div class="pv-head" data-sr="up">
      <div><span class="label">${esc(p.tag)} · ${esc(p.kind.toUpperCase())}</span><h1>${esc(p.name)}</h1></div>
      <div style="display:flex;flex-direction:column;gap:18px"><p class="pv-one">${esc(p.one)}</p><p class="pv-idea"><b>IDEA</b>${esc(p.idea)}</p>
        <div style="display:flex;flex-wrap:wrap;gap:12px"><a class="btn btn-acc" href="${esc(p.url)}" target="_blank" rel="noopener">Visit live site ↗</a><a class="btn btn-line" href="#contact">Start a similar project</a></div></div>
    </div>
    <div class="browser" data-sr="scale"><div class="bar"><i></i><i></i><i></i><span class="url">${esc(host(p.url))}</span><a href="${esc(p.url)}" target="_blank" rel="noopener">Open ↗</a></div>${img(p.slug, p.shot, p.alt, '(max-width: 1312px) calc(100vw - 32px), 1280px', ' class="shotfull" fetchpriority="high"')}</div>
    <div class="specs" data-sr="up"><div><span>ROLE</span><b>${esc(p.role)}</b></div><div><span>YEAR</span><b>${esc(p.year)}</b></div><div><span>TIMELINE</span><b>${esc(p.time)}</b></div><div><span>STACK</span><b>${esc(p.stack)}</b></div>${p.kind === 'Client work' ? '<div><span>TEAM</span><b>Built in collaboration</b></div>' : ''}</div>
    <div class="story">
      <div data-sr="up" data-d="0"><span class="label">01 · THE PROBLEM</span><h2>What wasn't working</h2><p>${esc(p.problem)}</p></div>
      <div data-sr="up" data-d="1"><span class="label">02 · THE BUILD</span><h2>What I built</h2><p>${esc(p.built)}</p></div>
      <div data-sr="up" data-d="2"><span class="label">03 · THE RESULT</span><h2>What changed</h2><ul class="results">${p.results.map((r) => `<li>${esc(r)}</li>`).join('')}</ul></div>
    </div>
    <div class="clean" data-sr="up"><span class="label">04 · NO DEBT</span><h2>Why it's still clean</h2><ul class="results">${p.clean.map((r) => `<li>${esc(r)}</li>`).join('')}</ul></div>
    <div class="layers" data-sr="up"><span style="color:var(--muted);margin-right:8px">ARCHITECTURE LAYERS</span>${layers}</div>
    <div class="related">
      <div class="sec-head" data-sr="up"><div><span class="label">MORE WORK</span><h2 class="h2" style="font-size:clamp(30px,3.5vw,44px)">Related projects</h2></div><a class="crumb" href="/work/">All case studies →</a></div>
      <div class="rule" data-sr="line"></div>
      <div class="grid3" style="gap:16px">
        ${rel}
      </div>
    </div>
  </div>
`;
  const url = SITE + path;
  const date = published(`work/${p.slug}/index.html`);
  return page({
    title: p.title, description: p.description, path, ogType: 'article', date,
    ogImage: `/img/og/${p.slug}.png`, ogAlt: `${p.name} case study by notechdebt`,
    jsonld: {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'WebPage', '@id': url + '#webpage', url, name: p.title, description: p.description, inLanguage: 'en', datePublished: date,
          isPartOf: { '@id': SITE + '/#website' }, about: { '@id': url + '#work' }, breadcrumb: { '@id': url + '#breadcrumb' },
          author: { '@id': SITE + '/#kristo' },
          primaryImageOfPage: { '@type': 'ImageObject', url: `${SITE}/img/${p.slug}.webp`, width: p.shot[0], height: p.shot[1] }
        },
        breadcrumb(path, [['Home', '/'], ['Case studies', '/work/'], [p.name]]),
        {
          '@type': 'CreativeWork', '@id': url + '#work', name: p.name, description: p.one, url: p.url,
          image: `${SITE}/img/${p.slug}.webp`, dateCreated: p.year, genre: p.tag,
          keywords: p.stack.split(' · ').join(', '),
          creator: { '@id': SITE + '/#kristo' }
        }
      ]
    },
    main
  });
}

function workIndex() {
  const cards = projects.map((p, i) => relatedCard(p, i % 3).replace('<h3 class="name">', '<h2 class="name">').replace('</h3>', '</h2>')).join('\n        ');
  const main = `  <div class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span aria-current="page">Case studies</span></nav>
    <div class="pv-head" data-sr="up">
      <div><span class="label">${projects.length} PROJECTS · ALL LIVE</span><h1>Case studies</h1></div>
      <p class="pv-one">Products and client systems I designed and built: AI valuations, a booking SaaS, a three.js configurator, a custom ERP, e-commerce and a law firm that ranks #1 on Google. Each one shows the problem, the build, the result and why it's still clean.</p>
    </div>
    <div class="rule" data-sr="line" style="margin-top:48px"></div>
    <div class="grid3" style="gap:16px">
        ${cards}
    </div>
  </div>
`;
  const url = SITE + WORK.path;
  const date = published('work/index.html');
  return page({
    title: WORK.title, path: WORK.path, date,
    description: 'Seven case studies by software architect Kristo Prifti: AI valuations, a booking SaaS, a three.js configurator, a custom ERP, e-commerce and law firm SEO.',
    ogImage: '/img/og/home.png', ogAlt: 'notechdebt case studies',
    jsonld: {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'CollectionPage', '@id': url + '#webpage', url, name: WORK.title, inLanguage: 'en', datePublished: date,
          isPartOf: { '@id': SITE + '/#website' }, breadcrumb: { '@id': url + '#breadcrumb' },
          mainEntity: { '@type': 'ItemList', itemListElement: projects.map((p, i) => ({ '@type': 'ListItem', position: i + 1, url: `${SITE}/work/${p.slug}/`, name: p.name })) }
        },
        breadcrumb(WORK.path, [['Home', '/'], ['Case studies']])
      ]
    },
    main
  });
}

function notFound() {
  const main = `  <div class="wrap notfound">
    <span class="label">404 · NOT FOUND</span>
    <h1 class="h1">This page was refactored away.</h1>
    <p>The link may be old or mistyped. Everything that still exists is one click from here.</p>
    <div style="display:flex;flex-wrap:wrap;gap:14px"><a class="btn btn-acc" href="/">Go to the homepage →</a><a class="btn btn-line" href="/work/">See the case studies</a></div>
  </div>
`;
  return page({
    title: 'Page not found | notechdebt', description: 'This page does not exist.', path: '/404.html',
    robots: 'noindex', ogImage: '/img/og/home.png', ogAlt: 'notechdebt', main
  });
}

// ---------- write pages ----------
const out = [];
function write(rel, html) {
  const file = join(ROOT, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, html);
  out.push(rel);
}
projects.forEach((p, i) => write(`work/${p.slug}/index.html`, projectPage(p, i)));
write('work/index.html', workIndex());
write('404.html', notFound());

// ---------- sitemap: lastmod is the last commit that touched the file, or today if it has uncommitted changes ----------
const today = new Date().toLocaleDateString('en-CA'); // YYYY-MM-DD in local time
function lastmod(rel) {
  try {
    const dirty = execFileSync('git', ['status', '--porcelain', '--', rel], { cwd: ROOT, encoding: 'utf8' }).trim();
    if (dirty) return today;
    return execFileSync('git', ['log', '-1', '--format=%cs', '--', rel], { cwd: ROOT, encoding: 'utf8' }).trim() || today;
  } catch { return today; }
}
const urls = [['/', 'index.html'], [WORK.path, 'work/index.html'], ...projects.map((p) => [`/work/${p.slug}/`, `work/${p.slug}/index.html`])];
writeFileSync(join(ROOT, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(([u, f]) => `  <url><loc>${SITE}${u}</loc><lastmod>${lastmod(f)}</lastmod></url>`).join('\n')}
</urlset>
`);
out.push('sitemap.xml');

// ---------- checks ----------
const missing = projects.flatMap((p) => [`img/${p.slug}.webp`, `img/${p.slug}-640.webp`, `img/${p.slug}-960.webp`, `img/og/${p.slug}.png`]).concat('img/og/home.png').filter((f) => !existsSync(join(ROOT, f)));
console.log(`Built ${out.length} files: ${out.join(', ')}`);
if (missing.length) console.warn(`Missing images (run node tools/images.mjs for og/*.png): ${missing.join(', ')}`);
